### PR TITLE
fixed dtge previews

### PR DESCRIPTION
**Pull request by wiedikerli**

### CODE REVIEW

**Comment by leekelleher** [comment]
Thanks @ninjaonsafari! :+1:  I'll try to review it during this week. :8ball: 

It does raise an interesting question about Umbraco package interoperability ... conceptually, should SafeMailLink even be aware of DTGE?  (I'm like 90% cool with it - just that niggley 10%) :wink:

**Comment by wiedikerli** [comment]
so i removed the dtge check :stuck_out_tongue:

**Comment by leekelleher** [comment]
(I wasn't meaning for you to remove it - was meant more of a discussion point :smiley:)

Does that fix still work for you?

**Comment by wiedikerli** [comment]
yeah but i also think its better that safemaillink doesnt know about dtge.
It was a quick fix for the dtge.

yeah it still works :wink:

**Comment by leekelleher** [comment]
Closing this PR. Upon review, checking the `UrlReferrer` isn't the solution to the issue, as this would bypass the encoding for any pages that the visitor will visitor immediately after visiting any of the reserved paths.

**Pull request closed without merging**
